TaskRequestApp/Pages/TicketPage/AssignedTicket.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Collections.Generic;
using TaskRequestApp.Models;
using TaskRequestApp.Repository;
using TaskRequestApp.Services;

namespace TaskRequestApp.Pages.TicketPage
{
    public class AssignedTicketModel : PageModel
    {
        private readonly TicketRepository _tRepo;
        private readonly CustomerRepository _cRepo;
        private readonly TicketServices _tServices;
        private readonly EmployeeRepository _eRepo;

        public AssignedTicketModel(TicketRepository tRepo, CustomerRepository cRepo, TicketServices ticketService, EmployeeRepository eRepo)
        {
            _tRepo = tRepo;
            _cRepo = cRepo;
            _tServices = ticketService;
            _eRepo = eRepo;
        }

        [BindProperty]
        public Ticket Ticket { get; set; }

        [BindProperty]
        public Employee EmployeeInput { get; set; }

        [BindProperty]
        public string selectedcustomerId { get; set; }

        [BindProperty]
        public List<Ticket> TicketInput { get; set; } = new List<Ticket>();

        [BindProperty]
        public List<Ticket> Tickets { get; set; }

        [BindProperty]
        public List<Employee> Employees { get; set; } = new List<Employee>();

        [BindProperty]
        public string Id { get; set; }

        public void OnGet()
        {
            Tickets = _tRepo.List();

            var employeeRepo = _eRepo.List();
            if (Tickets.Count != 0)
            {
                foreach (var item in Tickets)
                {
                    if (item.TicketType == TicketType.Assigned)
                    {
                        TicketInput.Add(item);
                    }
                    foreach (var item2 in employeeRepo)
                    {
                        if (item.employeeId == item2.Id)
                        {
                            Employees.Add(item2);
                        }
                    }
                }
            }

        }
    }
}

TaskRequestApp/Pages/TicketPage/TechDetails.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using TaskRequestApp.Models;
using TaskRequestApp.Repository;
using TaskRequestApp.Services;

namespace TaskRequestApp.Pages.TicketPage
{
    public class TechDetailsModel : PageModel
    {
        private readonly TicketRepository _tRepo;
        private readonly TicketServices _tService;
        private readonly CustomerRepository _cRepo;
        private readonly CustomerServices _cService;
        private readonly TicketServices ticketService;
        public TechDetailsModel(TicketRepository ticketRepository, CustomerRepository customerRepository, TicketServices ticketservices)
        {
            _tRepo = ticketRepository;
            _cRepo = customerRepository;
            this.ticketService = ticketservices;
        }
        
        [BindProperty]
        public LevelOfPriority priority { get; set; }
        [BindProperty]
        public LevelOfDifficulty difficulty { get; set; }
        public Ticket TicketInput { get; set; } = new Ticket();
        [BindProperty]
        public string Id { get; set; }
        [BindProperty]
        public string CustomerName { get; set; }
        public string CustomerId { get; set; }
        [BindProperty]
        public string selectedTicketId { get; set; }

        private Array Listdifficulty = Enum.GetValues(typeof(LevelOfDifficulty));

        private Array Listpriority = Enum.GetValues(typeof(LevelOfPriority));

        public void OnGet(string id)
        {
            Id = id;
            ViewData["Id"] = id;
            TicketInput = _tRepo.Find(id);
            CustomerId = TicketInput.customerId.ToString();
        }
        public void OnPostSetDifficulty()
        {
            TicketInput = _tRepo.Find(selectedTicketId);
            ticketService.SetDifficulty(TicketInput, difficulty);
        }
        public void OnPostSetPriority()
        {
            TicketInput = _tRepo.Find(selectedTicketId);
            ticketService.SetPriority(TicketInput, priority);
        }
        public void OnPostSave(string id)
        {
            if (ModelState.IsValid)
            {
                TicketInput = _tRepo.Find(selectedTicketId);
                TicketInput.TicketType = TicketType.ReadyForAssigned;
                _tRepo.Update(TicketInput);
            }
        }
    }
}

TaskRequestApp/Pages/TicketPage/WaitAssignee.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using TaskRequestApp.Models;
using TaskRequestApp.Repository;
using TaskRequestApp.Services;

namespace TaskRequestApp.Pages.TicketPage
{
    public class WaitAssigneeModel : PageModel
    {

        private readonly TicketRepository _tRepo;
        private readonly CustomerRepository _cRepo;
        private readonly TicketServices _tServices;
        private readonly EmployeeRepository _eRepo;

        [BindProperty]
        public List<Ticket> TicketInput { get; set; } = new List<Ticket>();

        public List<SelectListItem> SelectListItems { get; set; } = new List<SelectListItem>();

        [BindProperty]
        public List<Ticket> Tickets { get; set; }

        [BindProperty]
        public Ticket Ticket { get; set; } = new Ticket();

        [BindProperty]
        public Employee EmployeeInput { get; set; }

        [BindProperty]
        public string Id { get; set; }

        [BindProperty]
        public string TicketId { get; set; }

        public WaitAssigneeModel(TicketRepository tRepo, CustomerRepository cRepo, TicketServices ticketService, EmployeeRepository eRepo)
        {
            _tRepo = tRepo;
            _cRepo = cRepo;
            _tServices = ticketService;
            _eRepo = eRepo;
        }
        public void OnGet()
        {
            var Employees = _eRepo.List();

            SelectListItems = Employees.Select(a => new SelectListItem { Value = a.Id, Text = a.Name }).ToList();
            Tickets = _tRepo.List();
            if (Tickets.Count != 0)
            {
                foreach (var item in Tickets)
                {
                    if (item.TicketType == TicketType.ReadyForAssigned)
                    {
                        TicketInput.Add(item);
                    }
                }
            }
        }
        public void OnPostSave(string Id, string TicketId)
        {
            Id = Id;

            TicketId = TicketId;
            Ticket = _tRepo.Find(Id);
            Ticket.TicketType = TicketType.Assigned;
            Ticket.employeeId = Id;
            Ticket.AssigneeDate = DateTime.Now.Date;
            _tRepo.Update(Ticket);
            _tServices.AssignedTicket(ticket: Ticket, empId: EmployeeInput.Id, emp: EmployeeInput);
            _tServices.SetWorkShift(Emp: EmployeeInput, ticket: Ticket);
        }
    }
}

TaskRequestApp/Pages/TicketPage/AssignedTicket.cshtml
@page
@model TaskRequestApp.Pages.TicketPage.AssignedTicketModel
@{
}

<form method="post">
    <table border="1" width="100%">
        <thead>
            <tr>
                <td>subject</td>
                <td>description</td>
                <td>assignee</td>
                <td>Assigned date</td>
            </tr>
        </thead>
        <tbody>
            @for (int i = 0; i < Model.TicketInput.Count; i++)
            {
            <tr>
                <td>TicketInput[i].Subject</td>
                <td>TicketInput[i].Description</td>
                <td>Employees[i].Name</td>
                <td>TicketInput[i].AssigneeDate</td>
                <td>
                    <button type="submit"> asp-route-id="@Model.TicketInput[i].Id" asp-page-handler="close ticket">close ticket</button>
                </td>
            </tr>
            }
        </tbody>

    </table>

</form>

TaskRequestApp/Pages/TicketPage/OpenTicket.cshtml
@page
@model TaskRequestApp.Pages.TicketPage.OpenTicketModel
@{
}
<form method="post">
    @for (int i = 0; i <Model.OpenTickets.Count; i++)
    {
        <table>
            <tr>

                <td>
                    <input asp-for="OpenTickets[i].Subject" type="text" placeholder="subject" />
                </td>
                <td>
                    <input asp-for="OpenTickets[i].Description" type="text" placeholder="description" />
                </td>
                <td>
                    <input asp-for="OpenTickets[i].OpenDate"  placeholder="date" />
                </td>
                <td>
                    <a asp-page="./TechDetails" asp-route-id="@Model.OpenTickets[i].Id">Set Tech Details</a>
                </td>
            </tr>
        </table>
    }
</form>

TaskRequestApp/Pages/TicketPage/TechDetails.cshtml
@page
@model TaskRequestApp.Pages.TicketPage.TechDetailsModel
@{
}
<form id="1" method="post">
    <tr>
        <td>
            <input asp-for="@Model.TicketInput.Subject" type="text" placeholder="subject" />
            <input asp-for="@Model.TicketInput.Description" type="text" placeholder="description" />
            <input asp-for="@Model.TicketInput.OpenDate" type="text" placeholder="date" />
            <input asp-for="@Model.TicketInput.customerId" type="text" placeholder="customer" />
        </td>
    </tr>
</form>
<form id="2" method="post">
    @foreach (var item in Enum.GetValues(typeof(Models.LevelOfDifficulty)))
    {
        @Html.RadioButtonFor(m => m.difficulty, item) @item.ToString();
    }
    <input type="submit" value="Set"  asp-page-handler="SetDifficulty" />
    <input type="hidden" value="@Model.TicketInput.Id" asp-for="selectedTicketId" />
</form>
<form id="3" method="post">
    @foreach (var item in Enum.GetValues(typeof(Models.LevelOfPriority)))
    {
        @Html.RadioButtonFor(m => m.priority, item) @item.ToString();
    }
    <input type="submit" value="onayla" asp-page-handler="SetPriority" />
    <input type="hidden" value="@Model.TicketInput.Id" asp-for="selectedTicketId" />
    <input type="submit" value="Save" asp-page-handler="Save" />
</form>

TaskRequestApp/Pages/TicketPage/TicketCreate.cshtml
@page
@model TaskRequestApp.Pages.TicketPage.TicketCreateModel
@{
}
<form method="post">

    <input asp-for="TicketInput.Subject" />
    <span asp-validation-for="TicketInput.Subject"></span>

    <input asp-for="TicketInput.Description" />
    <span asp-validation-for="TicketInput.Description"></span>

    <select asp-for="TicketInput.customerId" 
            asp-items="Model.SelectListItems">

    </select>

    <input type="submit" value="Save" asp-page-handler="Save" />
</form>

TaskRequestApp/Pages/TicketPage/WaitAssignee.cshtml
@page
@model TaskRequestApp.Pages.TicketPage.WaitAssigneeModel
@{
}


<form method="post">
    <table border="1" width="100%">
        <thead>
            <tr>
                <th>subject</th>,
                <th>description</th>
                <th>difficulty</th>
                <th>priority</th>
                <th>assignee</th>
            </tr>
        </thead>
        <tbody>
            @for(int i=0; i < Model.TicketInput.Count; i++)
            {
            <tr>
                <td>@Model.TicketInput[i].Subject</td>
                <td>@Model.TicketInput[i].Description</td>
                <td>@Model.TicketInput[i].Difficulty</td>
                <td>@Model.TicketInput[i].Priority</td>
                <td>
                    <label>select employee</label>
                    @Html.DropDownListFor(x => x.Id, Model.SelectListItems, "seçim yapınız", Model.TicketInput[i].employeeId)
                    <input type="submit" value="save" asp-page-handler="Save" asp-route-ticketId="@Model.TicketInput[i].Id" />
                </td>
            </tr>
            }
        </tbody>

    </table>

</form>